
//const urlBase = 'http://localhost:8080/Services/';
//export const piece = urlBase + 'piece.php';
//export const pieceType = urlBase + 'pieceType.php';
//export const report = urlBase + 'report.php';
//export const employee = urlBase + 'employee.php';
//export const employeeType = urlBase + 'employeeType.php';
//export const incidence = urlBase + 'incidence.php';
//export const incidences = urlBase + 'incidences.php';
//export const counters = urlBase + 'counters.php';
//export const credentials = urlBase + 'credentials.php';
const urlBaseDotNet = 'http://localhost:8080/api/';
export const credentialsDotNet = urlBaseDotNet + 'Credentials/';
export const pieceDotNet = urlBaseDotNet + 'Piece/';
export const incidenceDotNet = urlBaseDotNet + 'Incidence/';
export const employeeDotNet = urlBaseDotNet + 'Employee/';
export const employeeTypeDotNet = urlBaseDotNet + 'EmployeeType/';
export const pieceTypeDotNet = urlBaseDotNet + 'PieceType/';
export const reportDotNet = urlBaseDotNet + 'Report/';