const urlBase = 'http://localhost:8080/Services/';
export const piece = urlBase + 'piece.php';
export const pieceType = urlBase + 'pieceType.php';
export const report = urlBase + 'report.php';
export const employee = urlBase + 'employee.php';
export const employeeType = urlBase + 'employeeType.php';
export const incidence = urlBase + 'incidence.php';
export const counters = urlBase + 'counters.php';
export const credentials = urlBase + 'credentials.php';